export const adsMock = [{
	id: '1',
	category_id: 1,
	type_id: 1,
	title: 'House of 230 m²',
	description: '',
	created_at: '',
	updated_at: '',
	pivot: {
		ad_id: 1,
		option_id: 1,
		value: '45435',
	},
	price: '790000',
	body: '',
	is_vip: 12,
	city_id: 1,
}, {
	id: '3',
	category_id: 2,
	type_id: 2,
	title: 'Tesla car',
	description: 'Amazing car',
	created_at: '',
	updated_at: '',
	pivot: {
		ad_id: 1,
		option_id: 1,
		value: '45435',
	},
	price: '50000',
	body: '',
	is_vip: 12,
	city_id: 1,
},
	// {
	// 	id: '4',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },{
	// 	id: '5',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },{
	// 	id: '6',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },{
	// 	id: '7',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },{
	// 	id: '8',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },{
	// 	id: '9',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },{
	// 	id: '10',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },{
	// 	id: '11',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },{
	// 	id: '12',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },
	// {
	// 	id: '13',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },
	// {
	// 	id: '14',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },
	// {
	// 	id: '15',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },
	// {
	// 	id: '16',
	// 	category_id: 2,
	// 	type_id: 2,
	// 	title: 'Tesla car',
	// 	description: 'Amazing car',
	// 	created_at: '',
	// 	updated_at: '',
	// 	pivot: {
	// 		ad_id: 1,
	// 		option_id: 1,
	// 		value: '45435',
	// 	},
	// 	price: '50000',
	// 	body: '',
	// 	is_vip: 12,
	// 	city_id: 1,
	// },

];



